service: backend-serverless-caching

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
    clusterSize: "0.5"
    ttlInSeconds: 3600
    dataEncrypted: false
    perKeyInvalidation:
      requireAuthorization: false

provider:
  name: aws
  stage: dev
  region: sa-east-1
  runtime: nodejs18.x
  architecture: arm64
  timeout: 10
  memorySize: 256
  logRetentionInDays: 1
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  environment:
    STAGE: "dev"
    REGION: ${self:provider.region}
    API_GATEWAY_ID: !Ref ApiGatewayRestApi
    MONGODB_URI: ${ssm:backend-serverless-caching-dev-mongodb}
  layers:
    - { Ref: LayerCommonLambdaLayer }
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "apigateway:DELETE"
          Resource:
            - Fn::Join:
                - ""
                - - "arn:aws:apigateway:"
                  - ${self:provider.region}
                  - "::/restapis/"
                  - { Ref: ApiGatewayRestApi }
                  - "/stages/"
                  - ${self:provider.stage}
                  - "/cache/data"

package:
  patterns:
    - "!node_modules/**"
    - "!layers/**"
    - "!package-lock.json"
    - "!package.json"
    - "!jsconfig.json"

layers:
  layerCommon:
    path: layers/layerCommon
    compatibleRuntimes:
      - nodejs18.x
    name: ${self:service}-${self:provider.stage}-layerCommon

functions:
  createCourse:
    handler: serverless/functions/Course/create.handler
    events:
      - http:
          path: /courses
          method: post

  listCourse:
    handler: serverless/functions/Course/list.handler
    events:
      - http:
          path: /courses
          method: get
          caching:
            enabled: true

  readCourse:
    handler: serverless/functions/Course/read.handler
    events:
      - http:
          path: /course/{courseID}
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.courseID
